#-------------------------------
# General Site Settings
title: YH's blog
logo: ml_icon.svg 
# 아이콘 제작자 <a href="https://www.flaticon.com/kr/authors/becris" title="Becris">Becris</a> from <a href="https://www.flaticon.com/kr/" title="Flaticon"> www.flaticon.com</a> 
description: Yoohwan personal blog


#-------------------------------
# Author Settings
author:
  name: Yoohwan Kwon
  image: post_image.jpg
  say-hello: Hello, I’m <strong>Yoohwan Kwon</strong>
  bio: I'm MS.student at Yonsei University. 
       I'm interested in about <strong>Machine Learning</strong>, <strong>Speech Signal Processing</strong>, and <strong>Speaker recognition</strong>.

       <a href="pdf/Yoohwan_CV.pdf" target="_blank">PDF.</a>

#-------------------------------
# Contact links
#twitter: https://twitter.com/ # Add your Twitter handle
#dribbble: https://dribbble.com/ # Add your Dribbble handle
#instagram: https://instagram.com/ # Add your Instagram handle
#pinterest: https://pinterest.com/ # Add your Pinterest handle
facebook: https://facebook.com/YoohwanKon  
github : https://github.com/YoohwanKwon
linkedin: https://www.linkedin.com/in/yoohwan-kwon-5594741b3/


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: yoohwan # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
